"""v5_create_primary_table

Revision ID: 2a3e07437b24
Revises: d6c5aa464cb2
Create Date: 2018-02-06 17:46:24.804769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a3e07437b24'
down_revision = 'd6c5aa464cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_primary_link',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('link_id', sa.INTEGER(), nullable=False),
    sa.Column('img_url', sa.VARCHAR(length=100), nullable=True),
    sa.Column('add_datetime', sa.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['tb_link.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_primary_link')
    # ### end Alembic commands ###
