"""v2_add_confirmed_column

Revision ID: 43d8c4279917
Revises: ca3d7baa59cb
Create Date: 2018-01-25 17:51:30.409111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy import Column, Boolean
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision = '43d8c4279917'
down_revision = 'ca3d7baa59cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', Column('confirmed', Boolean, server_default=expression.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_user', Column('confirmed', Boolean, server_default=expression.false()))
    # ### end Alembic commands ###
