"""v4_create_worthy_table

Revision ID: d6c5aa464cb2
Revises: 455aabce5081
Create Date: 2018-02-05 17:34:34.251144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6c5aa464cb2'
down_revision = '455aabce5081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_worthy_link',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('link_id', sa.INTEGER(), nullable=False),
    sa.Column('add_datetime', sa.DATETIME(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['tb_link.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_worthy_link')
    # ### end Alembic commands ###
